# Generated by Django 5.1.1 on 2024-11-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shoper', '0002_add_to_cart_add_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='productdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Brand', models.CharField(max_length=30)),
                ('Status', models.CharField(max_length=30)),
                ('Price', models.CharField(max_length=30)),
                ('quantity', models.CharField(max_length=30)),
                ('image_url', models.ImageField(default=None, upload_to='Uploads/')),
            ],
        ),
        migrations.RemoveField(
            model_name='add_to_cart',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='Add_cart',
        ),
        migrations.DeleteModel(
            name='Add_to_cart',
        ),
    ]
