# Generated by Django 5.1.1 on 2024-11-12 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shoper', '0003_productdetail_remove_add_to_cart_content_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productdetail',
            new_name='Cartdetail',
        ),
    ]
