# Generated by Django 5.1.1 on 2024-11-14 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shoper', '0005_rename_image_url_cartdetail_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdetail',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CartsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Brand', models.CharField(max_length=30)),
                ('Status', models.CharField(max_length=30)),
                ('Price', models.CharField(max_length=30)),
                ('quantity', models.CharField(max_length=30)),
                ('Image', models.ImageField(default=None, upload_to='Uploads/')),
                ('Region', models.CharField(max_length=20)),
                ('District', models.CharField(max_length=20)),
                ('Ward', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=10)),
                ('Contact_name', models.CharField(max_length=20)),
                ('First_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('House_no', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=20)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
