# Generated by Django 5.1.1 on 2024-11-14 19:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shoper', '0007_alter_cartdetail_user_alter_cartsdetails_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartsDetails',
            new_name='CartAdmin',
        ),
    ]
