# Generated by Django 5.1.1 on 2024-11-14 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shoper', '0008_rename_cartsdetails_cartadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartadmin',
            name='user',
        ),
    ]
