# Generated by Django 5.1.1 on 2024-11-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shoper', '0010_remove_cartdetail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartadmin',
            name='Email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cartadmin',
            name='Phone',
            field=models.CharField(max_length=50),
        ),
    ]
