# Generated by Django 5.1.1 on 2024-11-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shoper', '0011_alter_cartadmin_email_alter_cartadmin_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartadmin',
            name='Contact_name',
            field=models.CharField(max_length=100),
        ),
    ]
