# Generated by Django 5.1.1 on 2024-11-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shoper', '0012_alter_cartadmin_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerform',
            name='Contact_name',
            field=models.CharField(max_length=30),
        ),
    ]
